//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.27 at 01:33:00 PM IST 
//


package com.ssn.ws.rest.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="face_detection" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="boundingbox">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="tl">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="size">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="confidence" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="matches" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="score" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="pose">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="roll" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="yaw" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="pitch" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ori_img_size">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="usage">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="quota" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="api_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "url",
    "faceDetection",
    "oriImgSize",
    "usage"
})
@XmlRootElement(name = "SSNFaceRecognitionResponse")
public class SSNFaceRecognitionResponse {

    @XmlElement(required = true)
    protected String url;
    @XmlElement(name = "face_detection")
    protected List<SSNFaceRecognitionResponse.FaceDetection> face_detection;
    @XmlElement(name = "ori_img_size", required = true)
    protected SSNFaceRecognitionResponse.OriImgSize ori_img_size;
    @XmlElement(required = true)
    protected SSNFaceRecognitionResponse.Usage usage;
    protected int img_processed;
    
    
     /**
         * Gets the value of the img_index property.
         * 
         */
        public int getImgProcessed() {
            return img_processed;
        }

        /**
         * Sets the value of the img_index property.
         * 
         */
        public void setImgProcessed(int value) {
            this.img_processed = value;
        }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the faceDetection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faceDetection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaceDetection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SSNFaceRecognitionResponse.FaceDetection }
     * 
     * 
     */
    public List<SSNFaceRecognitionResponse.FaceDetection> getFaceDetection() {
        if (face_detection == null) {
            face_detection = new ArrayList<SSNFaceRecognitionResponse.FaceDetection>();
        }
        return this.face_detection;
    }
    
    

    /**
     * Gets the value of the oriImgSize property.
     * 
     * @return
     *     possible object is
     *     {@link SSNFaceRecognitionResponse.OriImgSize }
     *     
     */
    public SSNFaceRecognitionResponse.OriImgSize getOriImgSize() {
        return ori_img_size;
    }

    /**
     * Sets the value of the oriImgSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSNFaceRecognitionResponse.OriImgSize }
     *     
     */
    public void setOriImgSize(SSNFaceRecognitionResponse.OriImgSize value) {
        this.ori_img_size = value;
    }

    /**
     * Gets the value of the usage property.
     * 
     * @return
     *     possible object is
     *     {@link SSNFaceRecognitionResponse.Usage }
     *     
     */
    public SSNFaceRecognitionResponse.Usage getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSNFaceRecognitionResponse.Usage }
     *     
     */
    public void setUsage(SSNFaceRecognitionResponse.Usage value) {
        this.usage = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="boundingbox">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="tl">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="size">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="confidence" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="matches" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="score" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="pose">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="roll" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="yaw" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="pitch" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "boundingbox",
        "confidence",
        "name",
        "matches",
        "pose"
    })
    public static class FaceDetection {

        @XmlElement(required = true)
        protected SSNFaceRecognitionResponse.FaceDetection.Boundingbox boundingbox;
        protected float confidence;
        @XmlElement(required = true)
        protected String name;
        protected String img_index;
        protected List<SSNFaceRecognitionResponse.FaceDetection.Matches> matches;
        @XmlElement(required = true)
        protected SSNFaceRecognitionResponse.FaceDetection.Pose pose;

        /**
         * Gets the value of the boundingbox property.
         * 
         * @return
         *     possible object is
         *     {@link SSNFaceRecognitionResponse.FaceDetection.Boundingbox }
         *     
         */
        public SSNFaceRecognitionResponse.FaceDetection.Boundingbox getBoundingbox() {
            return boundingbox;
        }

        /**
         * Sets the value of the boundingbox property.
         * 
         * @param value
         *     allowed object is
         *     {@link SSNFaceRecognitionResponse.FaceDetection.Boundingbox }
         *     
         */
        public void setBoundingbox(SSNFaceRecognitionResponse.FaceDetection.Boundingbox value) {
            this.boundingbox = value;
        }

        /**
         * Gets the value of the confidence property.
         * 
         */
        public float getConfidence() {
            return confidence;
        }

        /**
         * Sets the value of the confidence property.
         * 
         */
        public void setConfidence(float value) {
            this.confidence = value;
        }
        
        /**
         * Gets the value of the img_index property.
         * 
         */
        public String getImgIndex() {
            return img_index;
        }

        /**
         * Sets the value of the img_index property.
         * 
         */
        public void setImgIndex(String value) {
            this.img_index = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the matches property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the matches property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMatches().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SSNFaceRecognitionResponse.FaceDetection.Matches }
         * 
         * 
         */
        public List<SSNFaceRecognitionResponse.FaceDetection.Matches> getMatches() {
            if (matches == null) {
                matches = new ArrayList<SSNFaceRecognitionResponse.FaceDetection.Matches>();
            }
            return this.matches;
        }

        /**
         * Gets the value of the pose property.
         * 
         * @return
         *     possible object is
         *     {@link SSNFaceRecognitionResponse.FaceDetection.Pose }
         *     
         */
        public SSNFaceRecognitionResponse.FaceDetection.Pose getPose() {
            return pose;
        }

        /**
         * Sets the value of the pose property.
         * 
         * @param value
         *     allowed object is
         *     {@link SSNFaceRecognitionResponse.FaceDetection.Pose }
         *     
         */
        public void setPose(SSNFaceRecognitionResponse.FaceDetection.Pose value) {
            this.pose = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tl">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="size">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tl",
            "size"
        })
        public static class Boundingbox {

            @XmlElement(required = true)
            protected SSNFaceRecognitionResponse.FaceDetection.Boundingbox.Tl tl;
            @XmlElement(required = true)
            protected SSNFaceRecognitionResponse.FaceDetection.Boundingbox.Size size;

            /**
             * Gets the value of the tl property.
             * 
             * @return
             *     possible object is
             *     {@link SSNFaceRecognitionResponse.FaceDetection.Boundingbox.Tl }
             *     
             */
            public SSNFaceRecognitionResponse.FaceDetection.Boundingbox.Tl getTl() {
                return tl;
            }

            /**
             * Sets the value of the tl property.
             * 
             * @param value
             *     allowed object is
             *     {@link SSNFaceRecognitionResponse.FaceDetection.Boundingbox.Tl }
             *     
             */
            public void setTl(SSNFaceRecognitionResponse.FaceDetection.Boundingbox.Tl value) {
                this.tl = value;
            }

            /**
             * Gets the value of the size property.
             * 
             * @return
             *     possible object is
             *     {@link SSNFaceRecognitionResponse.FaceDetection.Boundingbox.Size }
             *     
             */
            public SSNFaceRecognitionResponse.FaceDetection.Boundingbox.Size getSize() {
                return size;
            }

            /**
             * Sets the value of the size property.
             * 
             * @param value
             *     allowed object is
             *     {@link SSNFaceRecognitionResponse.FaceDetection.Boundingbox.Size }
             *     
             */
            public void setSize(SSNFaceRecognitionResponse.FaceDetection.Boundingbox.Size value) {
                this.size = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "width",
                "height"
            })
            public static class Size {

                protected float width;
                protected float height;

                /**
                 * Gets the value of the width property.
                 * 
                 */
                public float getWidth() {
                    return width;
                }

                /**
                 * Sets the value of the width property.
                 * 
                 */
                public void setWidth(float value) {
                    this.width = value;
                }

                /**
                 * Gets the value of the height property.
                 * 
                 */
                public float getHeight() {
                    return height;
                }

                /**
                 * Sets the value of the height property.
                 * 
                 */
                public void setHeight(float value) {
                    this.height = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "x",
                "y"
            })
            public static class Tl {

                protected float x;
                protected float y;

                /**
                 * Gets the value of the x property.
                 * 
                 */
                public float getX() {
                    return x;
                }

                /**
                 * Sets the value of the x property.
                 * 
                 */
                public void setX(float value) {
                    this.x = value;
                }

                /**
                 * Gets the value of the y property.
                 * 
                 */
                public float getY() {
                    return y;
                }

                /**
                 * Sets the value of the y property.
                 * 
                 */
                public void setY(float value) {
                    this.y = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="score" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tag",
            "score"
        })
        public static class Matches {

            @XmlElement(required = true)
            protected String tag;
            protected float score;

            /**
             * Gets the value of the tag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTag() {
                return tag;
            }

            /**
             * Sets the value of the tag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTag(String value) {
                this.tag = value;
            }

            /**
             * Gets the value of the score property.
             * 
             */
            public float getScore() {
                return score;
            }

            /**
             * Sets the value of the score property.
             * 
             */
            public void setScore(float value) {
                this.score = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="roll" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="yaw" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="pitch" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "roll",
            "yaw",
            "pitch"
        })
        public static class Pose {

            protected float roll;
            protected float yaw;
            protected float pitch;

            /**
             * Gets the value of the roll property.
             * 
             */
            public float getRoll() {
                return roll;
            }

            /**
             * Sets the value of the roll property.
             * 
             */
            public void setRoll(float value) {
                this.roll = value;
            }

            /**
             * Gets the value of the yaw property.
             * 
             */
            public float getYaw() {
                return yaw;
            }

            /**
             * Sets the value of the yaw property.
             * 
             */
            public void setYaw(float value) {
                this.yaw = value;
            }

            /**
             * Gets the value of the pitch property.
             * 
             */
            public float getPitch() {
                return pitch;
            }

            /**
             * Sets the value of the pitch property.
             * 
             */
            public void setPitch(float value) {
                this.pitch = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "width",
        "height"
    })
    public static class OriImgSize {

        protected float width;
        protected float height;

        /**
         * Gets the value of the width property.
         * 
         */
        public float getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         */
        public void setWidth(float value) {
            this.width = value;
        }

        /**
         * Gets the value of the height property.
         * 
         */
        public float getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         * 
         */
        public void setHeight(float value) {
            this.height = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="quota" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="api_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "quota",
        "status",
        "apiId"
    })
    public static class Usage {

        protected int quota;
        @XmlElement(required = true)
        protected String status;
        @XmlElement(name = "api_id", required = true)
        protected String api_id;

        /**
         * Gets the value of the quota property.
         * 
         */
        public int getQuota() {
            return quota;
        }

        /**
         * Sets the value of the quota property.
         * 
         */
        public void setQuota(int value) {
            this.quota = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the apiId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApiId() {
            return api_id;
        }

        /**
         * Sets the value of the apiId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApiId(String value) {
            this.api_id = value;
        }

    }

}
